# Redis 配置
redis:
  database: 0  #数据库索引(默认为0)
  host: 127.0.0.1
  port: 6379  #默认链接端口
  password:  #默认为空
  lettuce:
    pool:
      max-active: 8 #最大链接池
      max-wait: -1 #最大阻赛等待时间（使用负值没有限制）默认为-1
      max-idle: 8 #连接池中的最大空闲连接 默认 8
      min-idle: 0

spring:
  datasource:
    #业务数据库
    business:
      url: jdbc:mysql://localhost:3306/bar?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone = GMT&allowPublicKeyRetrieval=true
      username: root
      password: wang741
      driver-class-name: com.mysql.cj.jdbc.Driver


logging:
  level:
    root: debug
