mybatisGenerator:
  datasource:
    type: mysql
    address: localhost:3306
    db: bar
    username: root
    password: wang741

  targetPackage:
    model: com.study.generatorMybatis.entity
    mapper: com.study.generatorMybatis.mapper
    javaXmlFilesSamePackage: true

  targetRuntime: MyBatis3Simple
  mapperSuffixName: mapper
  java8: true
  disableExample: true

  plugins:
    comment: true
    lombok: true
    swagger: false
    mapperAnnotation: true
    serializable: false

  tables:
    - sub_content_info
    - theme
    - tribe
    - user_info
    - user_relation
